### ISSUE TITLE
Internal error for some .eml files

### ISSUE THREAD

**Issue by Boy132** [HugoHasenbein/redmine_more_previews#28]
**Problem:**
Some .eml Attachments throw an internal error because of the econding. Sadly I can not provide a file thats causing the issue as the content is confidential but the mail's content-type is `text/html; charset=iso-8859-1` and just contains simple text and one image. I will try to reproduce the problem with a mail I'm allowed to share.

**Logs:**
https://hastebin.com/arokomelit.apache

**Environment:**
Redmine version - 4.2.1.stable
Ruby version - 2.5.5-p157 (2019-03-15) [x86_64-linux-gnu]
Rails version - 5.2.5
Environment - production
Database adapter - Mysql2
Mailer queue - ActiveJob::QueueAdapters::AsyncAdapter
Mailer delivery - smtp

**Comment by Boy132** [comment]
[message.zip](https://github.com/HugoHasenbein/redmine_more_previews/files/6967045/message.zip)
See the attached file for an example.

**Comment by Boy132** [comment]
The name is the problem because it contains a "ö":
`From: =?iso-8859-1?Q?Sch=F6nau?= <snip>`

Characters like ä, ö and ü in the name of either the reciever or the sender seem to cause this issue.

**Comment by Boy132** [comment]
bump

**Comment by HugoHasenbein** [comment]
Dear Boy,

I am investigating on this. It seems, the way, the attachment is added to Redmine may help me to find the error. According to your logfiles the attachment contains ASCII-8-BIT text in the attachment's attribute 'description', which breaks in app/views/layouts/_file.html.erb:1, which is part of the core of Redmine. So the culprit is the program that writes the .eml attachment to the database.
Please, can you tell me how you add the .eml file to Redmine?

best regards

Stephan

**Comment by HugoHasenbein** [comment]
The message is camouflaged, which I understand. But it seems, the problem causing name has been -snipped- away as well.

**Comment by Boy132** [comment]
> Dear Boy, I am investigating on this. It seems, the way, the attachment is added to Redmine may help me to find the error. According to your logfiles the attachment contains ASCII-8-BIT text in the attachment's attribute 'description', which breaks in app/views/layouts/_file.html.erb:1, which is part of the core of Redmine. So the culprit is the program that writes the .eml attachment to the database. Please, can you tell me how you add the .eml file to Redmine? best regards Stephan

The .eml file is normally added as attachment.

> The message is camouflaged, which I understand. But it seems, the problem causing name has been -snipped- away as well.

Editing the .eml and manually change the subject or sender to the examples I gave above will reproduce the bug. (`From: =?iso-8859-1?Q?Sch=F6nau?=` or `Subject: =?iso-8859-1?Q?CO2-Feuerl=F6scher_?=`)

**Comment by HugoHasenbein** [comment]
Dear Boy,

try Version 2.0.7, now on GitHub. It should resolve the non-ascii headers issue in 'cliff'. I hope, this change does not reintroduce an old windows problem.

Best regards

Stephan

**Comment by Boy132** [comment]
> try Version 2.0.7, now on GitHub. It should resolve the non-ascii headers issue in 'cliff'.

I tested 2.0.7 and it did not resolve the problem. Still the same error:
[production.log](https://github.com/HugoHasenbein/redmine_more_previews/files/7020322/production.log)

**Comment by Boy132** [comment]
I also just realized that 2.0.7 breaks the Email body a bit:
![grafik](https://user-images.githubusercontent.com/8203120/130744297-9097ab57-86eb-4bb8-9022-8fce34778eb4.png)
Without the changes (2.0.6) it looks like this:
![grafik](https://user-images.githubusercontent.com/8203120/130744347-a6134cdd-5b63-4715-8b2e-2701bacf6924.png)

**Comment by Boy132** [comment]
Also loading the attachment "unsafe" works fine.
redmine.url/attachments/1024?unsafe=1

**Comment by jcatrysse** [comment]
I seem to have the same issue on « production » however on « test » this is working fine (though, I only get the email body, not the headers and attachments). Adding the « unsafe » parameter in the URL works fine.

**Comment by jcatrysse** [comment]
Thank you. This did not change the behavior, I am afraid. The mails are sometimes encoded into windows-1258 or windows-1252, maybe that can be an issue.

In production it only works with the unsafe=1 parameter.

![afbeelding](https://user-images.githubusercontent.com/23419642/154732702-8a08826e-07b6-4fd5-bcd0-6ee3181d0f3f.png)

But in test and production, I only get half of the beauty.

![afbeelding](https://user-images.githubusercontent.com/23419642/154733236-d563ab30-b8a2-494c-bf15-cb7da4e61d15.png)

**Comment by HugoHasenbein** [comment]
this behavior only for Cliff? Other previewers work?

**Comment by jcatrysse** [comment]
Changing `./converters/cliff/lib/cliff.rb` like this resolved the strange accent problem on _test_ but not on _production_ :
```
    unless unsafe
      doc = Nokogiri::HTML( html )
      doc.encoding = 'UTF-8'
      html = sweep( doc ).to_html
    end
```

I don't get the _encoding_ differences between the two...

**Comment by HugoHasenbein** [comment]
this change just sets the encoding. it does not encode.
try this - it may alleviate the problem.

  unless unsafe
      doc = Nokogiri::HTML( html )
      doc.encoding = charset
      html = sweep( doc ).to_html
    end

out in the wild the settings of charsets in emails sometimes is a mess, so we would have to guess the charset an encode our self
this, again may fail as well as not all windows encodings are transitive

    unless unsafe
      html = sweep( Nokogiri::HTML( RmpText.to_utf8(html) ) ).to_html
    end

**Comment by HugoHasenbein** [comment]
did you look in
config.encoding = "utf-8" # application.rb
and in your database.yml
production:
     adapter:  your_db
     host:     localhost
     encoding: utf8
development:
     adapter:  your_db
     host:     localhost
     encoding: utf8
test:
     adapter:  your_db
     host:     localhost
     encoding: utf8

**Comment by jcatrysse** [comment]
I will be testing all that next week, but it should he ok, it's a recent 
install using sql2 and mysql8 on utf8mb.
I will also test with a production environment on my test server, just to 
exclude server differences.

Maybe I'll check also on a classic linux server.

To be continued.

 Thank you and have a nice weekend.

**Comment by jcatrysse** [comment]
> did you look in config.encoding = "utf-8" # application.rb

Yes, this is the case.

>and in your database.yml production: adapter: your_db host: localhost encoding: utf8 development: adapter: your_db host: localhost encoding: utf8 test: adapter: your_db host: localhost encoding: utf8

I am using utf8mb4, but that seems to be correct for newer installations.

In the meanwhile, I activated a _production_ environment on my _test_ server and the result is identical (internal server error), so I can exclude server differences. It must have something to do with the difference between the _development / test_ and _production_ settings of Redmine.

For the moment, I get the best result (accent conversion on _test_) with this code (to be tested further):
```
    # sweep bad stuff from html
    unless unsafe
      doc = Nokogiri::HTML( html, nil, charset )
      doc.encoding = 'UTF-8'
      html = sweep( doc ).to_html
    end
```

However, when forcing `unsafe=1` I again get all the accent problems.

I need to leave now, but my next step is to search for the differences between test / development and production relating to the code page error. Maybe it is just a more stringent error management, I need to check.

It seems there is still some code page concerns in the `unsafe=0` flow, I will look at that later.

**Comment by jcatrysse** [comment]
For the accent problem, I tuned `./converters/cliff/lib/cliff.rb` to the code here below. This seems to fix the conversion in the _safe_ and the _unsafe_ mode.
```
    # get html
    html, charset = html( mail )

    # convert the charset to UTF-8
    doc = Nokogiri::HTML( html, nil, charset )
    doc.encoding = 'UTF-8'

    # sweep bad stuff from html
    unless unsafe
      html = sweep( doc ).to_html
    else
      html = doc.to_html
    end
```

I was able to work around the Internal server error by forcing the encoding of the filename to UTF-8. This is not a good fix, as it changed the original Redmine code, but it will potentially help to pinpoint the issue.

`app/views/layouts/_file.html.erb` - `.force_encoding('UTF-8')`
```
<div class="attachments">
<p><%= "#{@attachment.description.force_encoding('UTF-8')} - " unless @attachment.description.blank? %>
   <span class="author"><%= link_to_user(@attachment.author) %>, <%= format_time(@attachment.created_on) %></span></p>
</div>
```

**Comment by HugoHasenbein** [comment]
Dear Jan,

an html email does or does not have <meta> tags in it's header. One of the meta tags defines the charset. Sometimes the charset in the meta tag and the actually used charset differ.
If you use unsafe mode, then text is not sweeped and the html is indeed shown in the browser, whereby the browser reads and honors the meta tag. Possibly, the character conversion of the html email creates a BOM at the beginning of the html overriding the charset. The BOM having precedence over charset. All this is done by the browser with unsafe mode. In safe mode, the email is butched. I tried not to butch as 'bad' it like outlook does. The text is converted to utf-8, but the meta tag is left in the header. So in the end there is a header specifying some charset, the text however is utf-8, so the browser tries to interpret utf-8 as the charset in the meta tag.

So, when Nokogiri reads the html , after sweeping the bad stuff, the text should either be re-encoded to charset or, else the meta tag should be swept as well. Another alternative is to set the meta charset to utf-8, which is in the proposal below:

One fix could be in sweep

add to sweep the following lines:

    #
    # eventually change charset to utf-8
    #
    xml.xpath("//meta").each do |node|
      node.keys.each do |attribute|
        if attribute =~ /charset/i
          node.attr("charset").value = "UTF-8"
        end
      end
    end

just before the last line of sweep, before the terminating 'xml'

If you could send me the offending email, then I could check on my sid

best regards

Stephan

**Comment by jcatrysse** [comment]
Hello Dr.

Thank you again for your help. I implemented your code but unsuccessfully. I do, however, have some more and important information.

If you remember the difference in behavior between _test_ and _production_, that was due to the **caching** not being enabled.

On _production,_ the internal error happens when caching is **enabled**, and not when caching has been __disabled__. Likewise, it doesn't happen in the unsafe mode. Maybe unsafe is disabling some caching?

Could this be a hint to a solution?

This is the error in the logs:
```
Started GET "/attachments/387252?reload=1" for 10.212.134.10 at 2022-02-19 17:31:39 +0100
Processing by AttachmentsController#show as HTML
  Parameters: {"reload"=>"1", "id"=>"387252"}
  Current user: admin (id=1)
  Rendering plugins/redmine_more_previews/app/views/attachments/more_preview.html.erb within layouts/base
  Rendered plugins/redmine_more_previews/converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_attachment_contextual.html.erb (1.1ms)
  Rendered plugins/redmine_more_previews/converters/cliff/app/views/redmine_more_previews/hooks/_cliff_preview_attachment_top.html.erb (148.3ms)
  Rendered layouts/_file.html.erb (172.9ms)
  Rendered plugins/redmine_more_previews/app/views/attachments/more_preview.html.erb within layouts/base (173.4ms)
Completed 500 Internal Server Error in 189ms (ActiveRecord: 9.7ms)
  
ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    10: <p><%= "#{@attachment.description} - " unless @attachment.description.blank? %>
    11:    <span class="author"><%= link_to_user(@attachment.author) %>, <%= format_time(@attachment.created_on) %></span></p>
    12: </div>
    13: <div class="filecontent-container">
    14:   <%= yield %>
    15: </div>
    16: 
  
plugins/redmine_more_previews/app/views/attachments/more_preview.html.erb:54:in `block in _plugins_redmine_more_previews_app_views_attachments_more_preview_html_erb__2872474851497224052_251500'
app/views/layouts/_file.html.erb:13:in `_app_views_layouts__file_html_erb__373267665750349912_251520'
plugins/redmine_more_previews/app/views/attachments/more_preview.html.erb:8:in `_plugins_redmine_more_previews_app_views_attachments_more_preview_html_erb__2872474851497224052_251500'
plugins/redmine_more_previews/lib/redmine_more_previews/patches/attachments_controller_patch.rb:143:in `show_with_more_previews'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by HugoHasenbein** [comment]
production vs. development caching seems to be far away from incompatible character encodings. do you have an offending email you can share?

**Comment by jcatrysse** [comment]
I could send it in a private message... (I cannot share the message on the internet)
You could send me a message to jan.catrysse@gmail.com (I will semi hide my email address later on with an edit)
I can then send you the message.

When I bypass the sweep function, it still doesn't work. I don't think the problem is in the sweep function altogether.

**Comment by jcatrysse** [comment]
The patch I attach to this comment seems to resolve the issues for me, but I am quite sure there is another underlying problem I did not find. Maybe this van help another person with the same issue. Thank you for your help Dr. Stephan.
[corrected_codepage_issues + configurable path.txt](https://github.com/HugoHasenbein/redmine_more_previews/files/8102910/corrected_codepage_issues.%2B.configurable.path.txt)

**Comment by HugoHasenbein** [comment]
you may want to try version 2.0.8
